<?php

namespace Database\Seeders;

use App\Models\TrainingCertificate;
use Illuminate\Database\Seeder;

class TrainingCertificateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $trainings = [
            [
                'certificate_no' => 'S2C/9001-LA/2026/0001',
                'verification_id' => 'S2C-9001-LA-2026-0001',
                'candidate_name' => 'Muhammad Ali Khan',
                'candidate_id' => 'CAN-2026-0142',
                'course_title' => 'ISO 9001:2015 QMS Lead Auditor',
                'course_category' => 'Lead Auditor',
                'standard' => 'ISO 9001:2015',
                'training_duration' => '5 Days (40 Hours)',
                'training_provider' => 'S2 Certification Academy',
                'issuing_organization' => 'S2 Certification',
                'completion_date' => '2026-02-15',
                'issue_date' => '2026-02-20',
                'valid_until' => '2029-02-19',
                'status' => 'VALID',
                'remarks' => 'Successfully completed CQI/IRCA & S2 Accredited Lead Auditor Course with Distinction (Score: 92%).',
            ],
            [
                'certificate_no' => 'S2C/9001-AUD/2026/0002',
                'verification_id' => 'S2C-9001-AUD-2026-0002',
                'candidate_name' => 'Sara Ahmed',
                'candidate_id' => 'CAN-2026-0158',
                'course_title' => 'ISO 9001:2015 QMS Auditor',
                'course_category' => 'Auditor',
                'standard' => 'ISO 9001:2015',
                'training_duration' => '3 Days (24 Hours)',
                'training_provider' => 'S2 Certification Academy',
                'issuing_organization' => 'S2 Certification',
                'completion_date' => '2026-03-10',
                'issue_date' => '2026-03-12',
                'valid_until' => '2029-03-11',
                'status' => 'VALID',
                'remarks' => 'Passed written assessment and continuous auditing simulation.',
            ],
            [
                'certificate_no' => 'S2C/14001-LA/2026/0003',
                'verification_id' => 'S2C-14001-LA-2026-0003',
                'candidate_name' => 'Zubair Tariq',
                'candidate_id' => 'CAN-2026-0199',
                'course_title' => 'ISO 14001:2015 EMS Lead Auditor',
                'course_category' => 'Lead Auditor',
                'standard' => 'ISO 14001:2015',
                'training_duration' => '5 Days (40 Hours)',
                'training_provider' => 'S2 Certification Academy',
                'issuing_organization' => 'S2 Certification',
                'completion_date' => '2026-01-20',
                'issue_date' => '2026-01-25',
                'valid_until' => '2029-01-24',
                'status' => 'VALID',
                'remarks' => 'EMS Lead Auditor comprehensive workshop and practical environmental audit assessment.',
            ],
            [
                'certificate_no' => 'S2C/45001-LA/2026/0004',
                'verification_id' => 'S2C-45001-LA-2026-0004',
                'candidate_name' => 'Bilal Hassan',
                'candidate_id' => 'CAN-2026-0210',
                'course_title' => 'ISO 45001:2018 OH&S Lead Auditor',
                'course_category' => 'Lead Auditor',
                'standard' => 'ISO 45001:2018',
                'training_duration' => '5 Days (40 Hours)',
                'training_provider' => 'S2 Certification Academy',
                'issuing_organization' => 'S2 Certification',
                'completion_date' => '2025-11-14',
                'issue_date' => '2025-11-18',
                'valid_until' => '2028-11-17',
                'status' => 'VALID',
                'remarks' => 'Occupational Health and Safety Management System Lead Auditor qualification.',
            ],
            [
                'certificate_no' => 'S2C/IMS-LA/2026/0005',
                'verification_id' => 'S2C-IMS-LA-2026-0005',
                'candidate_name' => 'Ayesha Malik',
                'candidate_id' => 'CAN-2026-0235',
                'course_title' => 'Integrated Management System Lead Auditor (ISO 9001, 14001, 45001)',
                'course_category' => 'IMS Lead Auditor',
                'standard' => 'IMS (ISO 9001, 14001, 45001)',
                'training_duration' => '6 Days (48 Hours)',
                'training_provider' => 'S2 Certification Academy',
                'issuing_organization' => 'S2 Certification',
                'completion_date' => '2025-08-10',
                'issue_date' => '2025-08-15',
                'valid_until' => '2028-08-14',
                'status' => 'VALID',
                'remarks' => 'Integrated QHSE Management Systems Lead Auditor accreditation.',
            ],
            [
                'certificate_no' => 'S2C/27001-LA/2026/0006',
                'verification_id' => 'S2C-27001-LA-2026-0006',
                'candidate_name' => 'Hamza Arshad',
                'candidate_id' => 'CAN-2026-0268',
                'course_title' => 'ISO/IEC 27001:2022 ISMS Lead Auditor',
                'course_category' => 'Lead Auditor',
                'standard' => 'ISO 27001:2022',
                'training_duration' => '5 Days (40 Hours)',
                'training_provider' => 'S2 Certification Academy',
                'issuing_organization' => 'S2 Certification',
                'completion_date' => '2026-02-28',
                'issue_date' => '2026-03-04',
                'valid_until' => '2029-03-03',
                'status' => 'VALID',
                'remarks' => 'Information Security Management System Lead Auditor with Cyber Security Risk Assessment focus.',
            ],
            [
                'certificate_no' => 'S2C/22000-LA/2026/0007',
                'verification_id' => 'S2C-22000-LA-2026-0007',
                'candidate_name' => 'Fatima Noor',
                'candidate_id' => 'CAN-2026-0294',
                'course_title' => 'ISO 22000:2018 Food Safety Management System Lead Auditor',
                'course_category' => 'Lead Auditor',
                'standard' => 'ISO 22000:2018',
                'training_duration' => '5 Days (40 Hours)',
                'training_provider' => 'S2 Certification Academy',
                'issuing_organization' => 'S2 Certification',
                'completion_date' => '2026-01-15',
                'issue_date' => '2026-01-20',
                'valid_until' => '2029-01-19',
                'status' => 'VALID',
                'remarks' => 'FSMS HACCP and Food Defense Lead Auditor Certification.',
            ],
            [
                'certificate_no' => 'S2C/9001-IA/2025/0010',
                'verification_id' => 'S2C-9001-IA-2025-0010',
                'candidate_name' => 'Usman Raza',
                'candidate_id' => 'CAN-2025-0089',
                'course_title' => 'ISO 9001:2015 Internal Auditor Course',
                'course_category' => 'Internal Auditor',
                'standard' => 'ISO 9001:2015',
                'training_duration' => '2 Days (16 Hours)',
                'training_provider' => 'S2 Certification Academy',
                'issuing_organization' => 'S2 Certification',
                'completion_date' => '2023-01-10',
                'issue_date' => '2023-01-15',
                'valid_until' => '2026-01-14',
                'status' => 'EXPIRED',
                'remarks' => '3-year certificate validity cycle expired.',
            ],
            [
                'certificate_no' => 'S2C/45001-AUD/2026/0015',
                'verification_id' => 'S2C-45001-AUD-2026-0015',
                'candidate_name' => 'Farhan Sheikh',
                'candidate_id' => 'CAN-2026-0312',
                'course_title' => 'ISO 45001:2018 OH&S Auditor',
                'course_category' => 'Auditor',
                'standard' => 'ISO 45001:2018',
                'training_duration' => '3 Days (24 Hours)',
                'training_provider' => 'S2 Certification Academy',
                'issuing_organization' => 'S2 Certification',
                'completion_date' => '2026-02-01',
                'issue_date' => '2026-02-05',
                'valid_until' => '2029-02-04',
                'status' => 'SUSPENDED',
                'remarks' => 'Record under administrative verification review.',
            ],
            [
                'certificate_no' => 'S2C/14001-IA/2026/0020',
                'verification_id' => 'S2C-14001-IA-2026-0020',
                'candidate_name' => 'Zainab Qureshi',
                'candidate_id' => 'CAN-2026-0341',
                'course_title' => 'ISO 14001:2015 Environmental Management Internal Auditor',
                'course_category' => 'Internal Auditor',
                'standard' => 'ISO 14001:2015',
                'training_duration' => '2 Days (16 Hours)',
                'training_provider' => 'S2 Certification Academy',
                'issuing_organization' => 'S2 Certification',
                'completion_date' => '2026-03-01',
                'issue_date' => '2026-03-05',
                'valid_until' => '2029-03-04',
                'status' => 'VALID',
                'remarks' => 'Passed practical environmental aspect-impact audit examination.',
            ],
            [
                'certificate_no' => 'S2C/AW-9001/2026/0035',
                'verification_id' => 'S2C-AW-9001-2026-0035',
                'candidate_name' => 'Omer Farooq',
                'candidate_id' => 'CAN-2026-0388',
                'course_title' => 'ISO 9001:2015 Quality Management System Awareness & Implementation',
                'course_category' => 'Awareness Training',
                'standard' => 'ISO 9001:2015',
                'training_duration' => '1 Day (8 Hours)',
                'training_provider' => 'S2 Certification Academy',
                'issuing_organization' => 'S2 Certification',
                'completion_date' => '2026-02-10',
                'issue_date' => '2026-02-12',
                'valid_until' => null, // Lifetime
                'status' => 'VALID',
                'remarks' => 'Executive awareness workshop on Risk-Based Thinking in QMS.',
            ],
            [
                'certificate_no' => 'S2C/9001-LA/2024/0088',
                'verification_id' => 'S2C-9001-LA-2024-0088',
                'candidate_name' => 'Tariq Mehmood',
                'candidate_id' => 'CAN-2024-0044',
                'course_title' => 'ISO 9001:2015 QMS Lead Auditor',
                'course_category' => 'Lead Auditor',
                'standard' => 'ISO 9001:2015',
                'training_duration' => '5 Days (40 Hours)',
                'training_provider' => 'S2 Certification Academy',
                'issuing_organization' => 'S2 Certification',
                'completion_date' => '2024-04-10',
                'issue_date' => '2024-04-15',
                'valid_until' => '2027-04-14',
                'status' => 'REVOKED',
                'remarks' => 'Credential officially revoked due to disciplinary action.',
            ],
            [
                'certificate_no' => 'S2C/IMS-AUD/2026/0045',
                'verification_id' => 'S2C-IMS-AUD-2026-0045',
                'candidate_name' => 'Nadia Jamil',
                'candidate_id' => 'CAN-2026-0410',
                'course_title' => 'Integrated Management System Auditor (ISO 9001, 14001, 45001)',
                'course_category' => 'IMS Auditor',
                'standard' => 'IMS (ISO 9001, 14001, 45001)',
                'training_duration' => '4 Days (32 Hours)',
                'training_provider' => 'S2 Certification Academy',
                'issuing_organization' => 'S2 Certification',
                'completion_date' => '2026-03-05',
                'issue_date' => '2026-03-08',
                'valid_until' => '2029-03-07',
                'status' => 'VALID',
                'remarks' => 'Cross-standard audit integration training.',
            ],
            [
                'certificate_no' => 'S2C/50001-LA/2026/0050',
                'verification_id' => 'S2C-50001-LA-2026-0050',
                'candidate_name' => 'Rashid Ali',
                'candidate_id' => 'CAN-2026-0455',
                'course_title' => 'ISO 50001:2018 Energy Management System Lead Auditor',
                'course_category' => 'Lead Auditor',
                'standard' => 'ISO 50001:2018',
                'training_duration' => '5 Days (40 Hours)',
                'training_provider' => 'S2 Certification Academy',
                'issuing_organization' => 'S2 Certification',
                'completion_date' => '2026-01-28',
                'issue_date' => '2026-02-02',
                'valid_until' => '2029-02-01',
                'status' => 'VALID',
                'remarks' => 'EnMS Energy baseline auditing and energy performance indicators training.',
            ],
            [
                'certificate_no' => 'S2C/9001-LA/2025/0072',
                'verification_id' => 'S2C-9001-LA-2025-0072',
                'candidate_name' => 'Khurram Shehzad',
                'candidate_id' => 'CAN-2025-0199',
                'course_title' => 'ISO 9001:2015 QMS Lead Auditor',
                'course_category' => 'Lead Auditor',
                'standard' => 'ISO 9001:2015',
                'training_duration' => '5 Days (40 Hours)',
                'training_provider' => 'S2 Certification Academy',
                'issuing_organization' => 'S2 Certification',
                'completion_date' => '2025-06-20',
                'issue_date' => '2025-06-25',
                'valid_until' => '2028-06-24',
                'status' => 'CANCELLED',
                'remarks' => 'Certificate replaced and re-issued under updated accreditation scheme.',
            ]
        ];

        foreach ($trainings as $training) {
            TrainingCertificate::updateOrCreate(
                ['certificate_no' => $training['certificate_no']],
                $training
            );
        }
    }
}
